window.SCRIPT_WORD_EXTRAS = [
  { word: 'reservation', translation: 'бронь', emoji: '🛎️' },
  { word: 'dates', translation: 'даты', emoji: '📅' },
  { word: 'people', translation: 'люди / человек', emoji: '👥' },
  { word: 'child', translation: 'ребенок', emoji: '👶' },
  { word: 'category', translation: 'категория', emoji: '🏷️' },
  { word: 'room', translation: 'номер / комната', emoji: '🚪' },
  { word: 'lux', translation: 'люкс', emoji: '⭐' },
  { word: 'comfort', translation: 'комфорт', emoji: '🛏️' },
  { word: 'standard', translation: 'стандарт', emoji: '📋' },
  { word: 'wishes', translation: 'пожелания', emoji: '🙏' },
  { word: 'passport', translation: 'паспорт', emoji: '🪪' },
  { word: 'copy', translation: 'копия', emoji: '📄' },
  { word: 'documents', translation: 'документы', emoji: '📑' },
  { word: 'form', translation: 'форма', emoji: '📝' },
  { word: 'sign', translation: 'подписать', emoji: '✍️' },
  { word: 'signature', translation: 'подпись', emoji: '✍️' },
  { word: 'ready', translation: 'готово', emoji: '✅' },
  { word: 'key', translation: 'ключ', emoji: '🔑' },
  { word: 'guest', translation: 'гость', emoji: '🙂' },
  { word: 'card', translation: 'карта', emoji: '💳' },
  { word: 'food', translation: 'питание / еда', emoji: '🍽️' },
  { word: 'package', translation: 'пакет', emoji: '📦' },
  { word: 'daily', translation: 'ежедневно', emoji: '📆' },
  { word: 'breakfast', translation: 'завтрак', emoji: '🍳' },
  { word: 'lunch', translation: 'обед', emoji: '🥗' },
  { word: 'dinner', translation: 'ужин', emoji: '🍽️' },
  { word: 'full', translation: 'полный', emoji: '✅' },
  { word: 'board', translation: 'питание / пансион', emoji: '🍽️' },
  { word: 'served', translation: 'подается', emoji: '🍽️' },
  { word: 'restaurant', translation: 'ресторан', emoji: '🍴' },
  { word: 'price', translation: 'цена', emoji: '💰' },
  { word: 'rubles', translation: 'рубли', emoji: '₽' },
  { word: 'bill', translation: 'счет', emoji: '🧾' },
  { word: 'pay', translation: 'платить', emoji: '💳' },
  { word: 'cash', translation: 'наличные', emoji: '💵' },
  { word: 'credit', translation: 'кредитный', emoji: '💳' },
  { word: 'company', translation: 'компания', emoji: '🏢' },
  { word: 'left', translation: 'слева', emoji: '⬅️' },
  { word: 'right', translation: 'справа', emoji: '➡️' },
  { word: 'floor', translation: 'этаж', emoji: '🏢' },
  { word: 'second', translation: 'второй', emoji: '2️⃣' },
  { word: 'ground', translation: 'первый / нижний', emoji: '⬇️' },
  { word: 'reception', translation: 'ресепшн', emoji: '🛎️' },
  { word: 'open', translation: 'открыт / работает', emoji: '🟢' },
  { word: 'phone', translation: 'телефон', emoji: '☎️' },
  { word: 'luggage', translation: 'багаж', emoji: '🧳' },
  { word: 'fitness', translation: 'фитнес', emoji: '🏋️' },
  { word: 'spa', translation: 'спа', emoji: '💆' },
  { word: 'cafe', translation: 'кафе', emoji: '☕' },
  { word: 'website', translation: 'сайт', emoji: '🌐' },
  { word: 'information', translation: 'информация', emoji: 'ℹ️' },
  { word: 'taxi', translation: 'такси', emoji: '🚕' },
  { word: 'address', translation: 'адрес', emoji: '📍' },
  { word: 'time', translation: 'время', emoji: '⏰' },
  { word: 'city', translation: 'город', emoji: '🏙️' },
  { word: 'visa', translation: 'виза', emoji: '🛂' },
  { word: 'migration', translation: 'миграция', emoji: '🛂' },
  { word: 'anything', translation: 'что-нибудь', emoji: '❓' },
  { word: 'else', translation: 'еще', emoji: '➕' },
  { word: 'nice', translation: 'приятный / хороший', emoji: '🙂' },
  { word: 'morning', translation: 'утро', emoji: '🌅' },
  { word: 'afternoon', translation: 'день', emoji: '☀️' },
  { word: 'evening', translation: 'вечер', emoji: '🌙' },
  { word: 'please', translation: 'пожалуйста', emoji: '🙏' },
  { word: 'help', translation: 'помочь', emoji: '🤝' },
  { word: 'name', translation: 'имя', emoji: '🏷️' },
  { word: 'with', translation: 'с / вместе с', emoji: '🔗' },
  { word: 'need', translation: 'нужно', emoji: '❗' },
  { word: 'may', translation: 'можно / могу', emoji: '✅' },
  { word: 'make', translation: 'сделать', emoji: '🛠️' },
  { word: 'fill', translation: 'заполнить', emoji: '📝' },
  { word: 'here', translation: 'здесь', emoji: '📍' },
  { word: 'your', translation: 'ваш', emoji: '👉' },
  { word: 'have', translation: 'иметь / есть', emoji: '📌' },
  { word: 'what', translation: 'что / какой', emoji: '❓' },
  { word: 'which', translation: 'какой', emoji: '❓' },
  { word: 'many', translation: 'много', emoji: '🔢' },
  { word: 'old', translation: 'лет / старый', emoji: '🎂' },
  { word: 'birth', translation: 'рождение', emoji: '🎂' },
  { word: 'certificate', translation: 'свидетельство', emoji: '📄' },
  { word: 'twenty', translation: 'двадцать', emoji: '20' },
  { word: 'seven', translation: 'семь', emoji: '7' },
  { word: 'twenty-four-seven', translation: '24/7 / круглосуточно', emoji: '🕛' },
  { word: 'hb', translation: 'HB / завтрак и обед или ужин', emoji: '🍳' },
  { word: 'fb', translation: 'FB / завтрак, обед и ужин', emoji: '🍽️' },
  { word: 'march', translation: 'март', emoji: '📅' },
  { word: 'number', translation: 'номер / число', emoji: '🔢' },
  { word: 'ok', translation: 'хорошо / ок', emoji: '✅' },
  { word: 'planning', translation: 'планирует', emoji: '📅' },
  { word: 'stayed', translation: 'проживали / остановились', emoji: '🏨' },
  { word: '10', translation: 'десять', emoji: '🔟' },
  { word: '20', translation: 'двадцать', emoji: '20' },
  { word: '28', translation: 'двадцать восемь', emoji: '28' },
  { word: 'sir', translation: 'сэр', emoji: '🙂' },
  { word: 'madam', translation: 'мадам', emoji: '🙂' },
  { word: 'thank', translation: 'спасибо / благодарить', emoji: '🙏' },
  { word: 'when', translation: 'когда', emoji: '⏱️' },
  { word: 'came', translation: 'пришел / вернулся', emoji: '↩️' },
  { word: 'back', translation: 'назад / обратно', emoji: '↩️' },
  { word: 'window', translation: 'окно', emoji: '🪟' },
  { word: 'around', translation: 'вокруг / по комнате', emoji: '🔁' },
  { word: 'happened', translation: 'произошло', emoji: '⚠️' },
  { word: 'important', translation: 'важный', emoji: '❗' },
  { word: 'confirm', translation: 'подтвердить / уточнить', emoji: '✅' },
  { word: 'first', translation: 'сначала', emoji: '1️⃣' },
  { word: 'send', translation: 'отправить', emoji: '📨' },
  { word: 'housekeeping', translation: 'служба уборки / housekeeping', emoji: '🧹' },
  { word: 'supervisor', translation: 'супервайзер / старший', emoji: '👤' },
  { word: 'maid', translation: 'горничная', emoji: '🧹' },
  { word: 'collect', translation: 'собрать', emoji: '📄' },
  { word: 'put', translation: 'привести / положить', emoji: '📌' },
  { word: 'order', translation: 'порядок', emoji: '✅' },
  { word: 'convenient', translation: 'удобный', emoji: '👌' },
  { word: 'wish', translation: 'хотите / желание', emoji: '🙏' },
  { word: 'also', translation: 'также', emoji: '➕' },
  { word: 'speak', translation: 'поговорить', emoji: '💬' },
  { word: 'team', translation: 'команда', emoji: '👥' },
  { word: 'cannot', translation: 'не могу', emoji: '🚫' },
  { word: 'say', translation: 'сказать', emoji: '💬' },
  { word: 'yet', translation: 'пока еще', emoji: '⏳' },
  { word: 'why', translation: 'почему', emoji: '❓' },
  { word: 'missing', translation: 'пропавший / не хватает', emoji: '❓' },
  { word: 'damaged', translation: 'поврежденный', emoji: '⚠️' },
  { word: 'apology', translation: 'извинение', emoji: '🙏' },
  { word: 'inconvenience', translation: 'неудобство', emoji: '⚠️' },
  { word: 'complimentary', translation: 'бесплатный / комплимент от отеля', emoji: '🎁' },
  { word: 'fruit', translation: 'фрукты', emoji: '🍎' },
  { word: 'plate', translation: 'тарелка', emoji: '🍽️' },
  { word: 'later', translation: 'позже', emoji: '⏳' },
  { word: 'sure', translation: 'убедиться / точно', emoji: '✅' },
  { word: 'everything', translation: 'все', emoji: '✅' },
  { word: 'terrible', translation: 'ужасно', emoji: '😟' },
  { word: 'everywhere', translation: 'везде / повсюду', emoji: '↔️' },
  { word: 'fully', translation: 'полностью', emoji: '💯' },
  { word: 'upset', translation: 'расстроен / зол', emoji: '😠' },
  { word: 'too', translation: 'тоже', emoji: '➕' },
  { word: 'away', translation: 'сразу / прочь', emoji: '⚡' },
  { word: 'inform', translation: 'сообщить', emoji: 'ℹ️' },
  { word: 'duty', translation: 'дежурный', emoji: '🛎️' },
  { word: 'manager', translation: 'менеджер', emoji: '👔' },
  { word: 'immediately', translation: 'немедленно', emoji: '⚡' },
  { word: 'permission', translation: 'разрешение', emoji: '✅' },
  { word: 'papers', translation: 'бумаги / документы', emoji: '📄' },
  { word: 'carefully', translation: 'аккуратно', emoji: '🤲' },
  { word: 'service', translation: 'сервис / обслуживание', emoji: '🛎️' },
  { word: 'offer', translation: 'предложить', emoji: '🤝' },
  { word: 'tea', translation: 'чай', emoji: '🍵' },
  { word: 'coffee', translation: 'кофе', emoji: '☕' },
  { word: 'lobby', translation: 'лобби', emoji: '🏨' },
  { word: 'while', translation: 'пока', emoji: '⏳' },
  { word: 'care', translation: 'позаботиться / забота', emoji: '🤝' },
  { word: 'concern', translation: 'беспокойство', emoji: '⚠️' },
  { word: 'private', translation: 'личный / приватный', emoji: '🔒' },
  { word: 'touch', translation: 'трогать', emoji: '✋' },
  { word: 'without', translation: 'без', emoji: '🚫' },
  { word: 'together', translation: 'вместе', emoji: '👥' },
  { word: 'incident', translation: 'инцидент', emoji: '⚠️' },
  { word: 'report', translation: 'отчет / акт', emoji: '📋' },
  { word: 'entered', translation: 'вошел', emoji: '🚪' },
  { word: 'who', translation: 'кто', emoji: '❓' }
];
