window.SCRIPT_WORD_EXTRAS = [
  { word: 'reservation', translation: 'бронь', emoji: '🛎️' },
  { word: 'dates', translation: 'даты', emoji: '📅' },
  { word: 'people', translation: 'люди / человек', emoji: '👥' },
  { word: 'child', translation: 'ребенок', emoji: '👶' },
  { word: 'category', translation: 'категория', emoji: '🏷️' },
  { word: 'room', translation: 'номер / комната', emoji: '🚪' },
  { word: 'lux', translation: 'люкс', emoji: '⭐' },
  { word: 'comfort', translation: 'комфорт', emoji: '🛏️' },
  { word: 'standard', translation: 'стандарт', emoji: '📋' },
  { word: 'wishes', translation: 'пожелания', emoji: '🙏' },
  { word: 'passport', translation: 'паспорт', emoji: '🪪' },
  { word: 'copy', translation: 'копия', emoji: '📄' },
  { word: 'documents', translation: 'документы', emoji: '📑' },
  { word: 'form', translation: 'форма', emoji: '📝' },
  { word: 'sign', translation: 'подписать', emoji: '✍️' },
  { word: 'signature', translation: 'подпись', emoji: '✍️' },
  { word: 'ready', translation: 'готово', emoji: '✅' },
  { word: 'key', translation: 'ключ', emoji: '🔑' },
  { word: 'guest', translation: 'гость', emoji: '🙂' },
  { word: 'card', translation: 'карта', emoji: '💳' },
  { word: 'food', translation: 'питание / еда', emoji: '🍽️' },
  { word: 'package', translation: 'пакет', emoji: '📦' },
  { word: 'daily', translation: 'ежедневно', emoji: '📆' },
  { word: 'breakfast', translation: 'завтрак', emoji: '🍳' },
  { word: 'lunch', translation: 'обед', emoji: '🥗' },
  { word: 'dinner', translation: 'ужин', emoji: '🍽️' },
  { word: 'full', translation: 'полный', emoji: '✅' },
  { word: 'board', translation: 'питание / пансион', emoji: '🍽️' },
  { word: 'served', translation: 'подается', emoji: '🍽️' },
  { word: 'restaurant', translation: 'ресторан', emoji: '🍴' },
  { word: 'price', translation: 'цена', emoji: '💰' },
  { word: 'rubles', translation: 'рубли', emoji: '₽' },
  { word: 'bill', translation: 'счет', emoji: '🧾' },
  { word: 'pay', translation: 'платить', emoji: '💳' },
  { word: 'cash', translation: 'наличные', emoji: '💵' },
  { word: 'credit', translation: 'кредитный', emoji: '💳' },
  { word: 'company', translation: 'компания', emoji: '🏢' },
  { word: 'left', translation: 'слева', emoji: '⬅️' },
  { word: 'right', translation: 'справа', emoji: '➡️' },
  { word: 'floor', translation: 'этаж', emoji: '🏢' },
  { word: 'second', translation: 'второй', emoji: '2️⃣' },
  { word: 'ground', translation: 'первый / нижний', emoji: '⬇️' },
  { word: 'reception', translation: 'ресепшн', emoji: '🛎️' },
  { word: 'open', translation: 'открыт / работает', emoji: '🟢' },
  { word: 'phone', translation: 'телефон', emoji: '☎️' },
  { word: 'luggage', translation: 'багаж', emoji: '🧳' },
  { word: 'fitness', translation: 'фитнес', emoji: '🏋️' },
  { word: 'spa', translation: 'спа', emoji: '💆' },
  { word: 'cafe', translation: 'кафе', emoji: '☕' },
  { word: 'website', translation: 'сайт', emoji: '🌐' },
  { word: 'information', translation: 'информация', emoji: 'ℹ️' },
  { word: 'taxi', translation: 'такси', emoji: '🚕' },
  { word: 'address', translation: 'адрес', emoji: '📍' },
  { word: 'time', translation: 'время', emoji: '⏰' },
  { word: 'city', translation: 'город', emoji: '🏙️' },
  { word: 'visa', translation: 'виза', emoji: '🛂' },
  { word: 'migration', translation: 'миграция', emoji: '🛂' },
  { word: 'anything', translation: 'что-нибудь', emoji: '❓' },
  { word: 'else', translation: 'еще', emoji: '➕' },
  { word: 'nice', translation: 'приятный / хороший', emoji: '🙂' },
  { word: 'morning', translation: 'утро', emoji: '🌅' },
  { word: 'afternoon', translation: 'день', emoji: '☀️' },
  { word: 'evening', translation: 'вечер', emoji: '🌙' },
  { word: 'please', translation: 'пожалуйста', emoji: '🙏' },
  { word: 'help', translation: 'помочь', emoji: '🤝' },
  { word: 'name', translation: 'имя', emoji: '🏷️' },
  { word: 'with', translation: 'с / вместе с', emoji: '🔗' },
  { word: 'need', translation: 'нужно', emoji: '❗' },
  { word: 'may', translation: 'можно / могу', emoji: '✅' },
  { word: 'make', translation: 'сделать', emoji: '🛠️' },
  { word: 'fill', translation: 'заполнить', emoji: '📝' },
  { word: 'here', translation: 'здесь', emoji: '📍' },
  { word: 'your', translation: 'ваш', emoji: '👉' },
  { word: 'have', translation: 'иметь / есть', emoji: '📌' },
  { word: 'what', translation: 'что / какой', emoji: '❓' },
  { word: 'which', translation: 'какой', emoji: '❓' },
  { word: 'many', translation: 'много', emoji: '🔢' },
  { word: 'old', translation: 'лет / старый', emoji: '🎂' },
  { word: 'birth', translation: 'рождение', emoji: '🎂' },
  { word: 'certificate', translation: 'свидетельство', emoji: '📄' },
  { word: 'twenty', translation: 'двадцать', emoji: '20' },
  { word: 'seven', translation: 'семь', emoji: '7' },
  { word: 'twenty-four-seven', translation: '24/7 / круглосуточно', emoji: '🕛' },
  { word: 'hb', translation: 'HB / завтрак и обед или ужин', emoji: '🍳' },
  { word: 'fb', translation: 'FB / завтрак, обед и ужин', emoji: '🍽️' },
  { word: 'march', translation: 'март', emoji: '📅' },
  { word: 'number', translation: 'номер / число', emoji: '🔢' },
  { word: 'ok', translation: 'хорошо / ок', emoji: '✅' },
  { word: 'planning', translation: 'планирует', emoji: '📅' },
  { word: 'stayed', translation: 'проживали / остановились', emoji: '🏨' },
  { word: '10', translation: 'десять', emoji: '🔟' },
  { word: '20', translation: 'двадцать', emoji: '20' },
  { word: '28', translation: 'двадцать восемь', emoji: '28' }
];
